# VERSION 0.1
# DOCKER-VERSION  1.7.0
# AUTHOR:         Antonio Lain <antlai@cafjs.com>
# DESCRIPTION:    Template for armv7
# TO_BUILD:
# TO_RUN:
#

FROM gcr.io/cafjs-k8/root-rpi2armhf

ENTRYPOINT ["node"]

CMD [ "./index.js" ]
